version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  btd:
    jobs:
      - orb-tools/increment:
          orb-path: orb/deployhub-orb.yml
          orb-ref: deployhub/deployhub-orb
          publish-token-variable: $CIRCLECI_DEV_API_TOKEN
          segment: minor
          validate: true
