version: 2.1
description: >
  DeployHub Integration. This Orb approves, moves, updates microservices, assigns application versions, and
  deploys objects passing in data between the CircleCI pipeline to DeployHub.

display:
  home_url: https://www.deployhub.com/
  source_url: https://github.com/DeployHubProject/deployhub-orb

executors:
    default:
      description: "Docker image for interacting with DeployHub"
      docker:
        - image: circlecipublic/docker-orb-test

commands:  
  microservice_version_update:
    description: "Update the microservice or component with git and build data"
    parameters:
      dhuser:
        description: "Name of env var storing UserId to access DeployHub"
        type: env_var_name
        default: DH_USERID
      dhpass:
        description: "Name of env var storing dhpass to access DeployHub"
        type: env_var_name
        default: DH_PASSWORD
      dhurl:
        description: "Name of env var storing URL to the DeployHub Server"
        type: env_var_name
        default: DH_SERVERURL
      application:
        description: "Application Name to associate the component to"
        type: string
      appversion:
        description: "Application Version to associate the component to"
        type: string
        default: "" 
      compname:
        description: "Component Name being updated"
        type: string
      compversion:
        description: "Component Version being updated"
        type: string 
      comptype:
        description: "Type of component, --docker or --file"
        type: string   
      helmchart:
        description: "Helm Chart Name"
        type: string   
      dockersha:
        description: "sha of the container"
        type: string  
      dockerrepo:
        description: "docker repo from push"
        type: string
      dockertag:
        description: "docker tag for the image"
        type: string                
      builddate:
        description: "Build Date"
        type: string
      gitrepo:
        description: "Git Repo Name"
        type: string
      giturl:
        description: "Git Url"
        type: string
      gitcommit:
        description: "Git Commit"
        type: string
      gitbranch:
          description: "Git Branch"
          type: string  
      gittag:
          description: "Git Tag"
          type: string          
      buildid:
        description: "Build Id"
        type: string
      buildurl:
        description: "Build Url"
        type: string  
      buildnumber:
        description: "Build Number"
        type: string 
      customaction:
        description: "Custom Action"
        type: string
      preaction:
        description: "Pre Action"
        type: string 
      postaction:
        description: "Post Action"
        type: string                                                                   
    steps:
      - run:
          name: Update microservice or component
          command: >
            env > /tmp/env_file;
            docker run --env-file=/tmp/env_file quay.io/deployhub/compupdate:latest 
            updatecomp
            --dhuser "$<< parameters.dhuser >>"
            --dhpass "$<< parameters.dhpass >>"
            --dhurl "$<< parameters.dhurl >>"
            --appname "<< parameters.application >>"
            --appversion "<< parameters.appversion >>"
            --appautoinc "Y"
            --compname "<< parameters.compname >>"
            --compversion "<< parameters.compversion >>"
            << parameters.comptype >>
            --compattr "GitCommit:<< parameters.gitcommit >>" 
            --compattr "GitUrl:<< parameters.giturl >>" 
            --compattr "GitRepo:<< parameters.gitrepo >>" 
            --compattr "GitBranch:<< parameters.gitbranch >>"
            --compattr "GitTag:<< parameters.gittag >>"
            --compattr "Chart:<< parameters.helmchart >>"
            --compattr "DockerSha:<< parameters.dockersha >>"
            --compattr "DockerBuildDate:<< parameters.builddate >>"
            --compattr "DockerRepo:<< parameters.dockerrepo >>"
            --compattr "DockerTag:<< parameters.dockertag >>"
            --compattr "BuildId:<< parameters.buildid >>"
            --compattr "BuildUrl:<< parameters.buildurl >>"
            --compattr "BuildNumber:<< parameters.buildnumber >>"
            --compattr "CustomAction:<< parameters.customaction >>"
            --compattr "PreAction:<< parameters.preaction >>"
            --compattr "PostAction:<< parameters.postaction >>"            

  approve:
    description: "Approves an Application Version for the current stage of the pipeline"
    parameters:
      dhuser:
        description: "Name of env var storing UserId to access DeployHub"
        type: env_var_name
        default: DH_USERID
      dhpass:
        description: "Name of env var storing dhpass to access DeployHub"
        type: env_var_name
        default: DH_PASSWORD
      dhurl:
        description: "Name of env var storing URL to the DeployHub Server"
        type: env_var_name
        default: DH_SERVERURL
      application:
        description: "Application Name to Approve"
        type: string
      appversion:
        description: "Application Version to Approve"
        type: string        

    steps:
      - run:
          name: Approve Application Version
          command: >
            env > /tmp/env_file;
            docker run --env-file=/tmp/env_file quay.io/deployhub/compupdate:latest 
            approve
            --dhuser "$<< parameters.dhuser >>"
            --dhpass "$<< parameters.dhpass >>"
            --dhurl "$<< parameters.dhurl >>"
            --appname "<< parameters.application >>"
            --appversion "<< parameters.appversion >>"

  move:
    description: "Moves an Application Version from the 'from' stage of the pipeline to another stage using the Move Task"
    parameters:
      dhuser:
        description: "Name of env var storing UserId to access DeployHub"
        type: env_var_name
        default: DH_USERID
      dhpass:
        description: "Name of env var storing dhpass to access DeployHub"
        type: env_var_name
        default: DH_PASSWORD
      dhurl:
        description: "Name of env var storing URL to the DeployHub Server"
        type: env_var_name
        default: DH_SERVERURL
      application:
        description: "Application Name to Move"
        type: string
      appversion:
        description: "Application Version to Move"
        type: string    
      from_domain:
        description: "Pipeline stage to move from"
        type: string
      move_task:
        description: "'Move Task' used to move the application version to desired stage"
        type: string                

    steps:
    - run:
        name: Move an Application Version through the pipeline
        command: >
          env > /tmp/env_file;
          docker run --env-file=/tmp/env_file quay.io/deployhub/compupdate:latest  
          move
          --dhuser "$<< parameters.dhuser >>"
          --dhpass "$<< parameters.dhpass >>"
          --dhurl "$<< parameters.dhurl >>"
          --appname "<< parameters.application >>"
          --appversion "<< parameters.appversion >>"
          --from_domain "<< parameters.from_domain >>"
          --task "<< parameters.move_task >>"                

  deploy:
    description: "Deploys an Application Version to an Environment"
    parameters:
      dhuser:
        description: "Name of env var storing UserId to access DeployHub"
        type: env_var_name
        default: DH_USERID
      dhpass:
        description: "Name of env var storing dhpass to access DeployHub"
        type: env_var_name
        default: DH_PASSWORD
      dhurl:
        description: "Name of env var storing URL to the DeployHub Server"
        type: env_var_name
        default: DH_SERVERURL
      application:
        description: "Application Name to Deploy"
        type: string
      appversion:
          description: "Application Version to Deploy"
          type: string    
      environment:
        description: "Environment to Deploy to"
        type: string             

    steps:
    - run:
        name: Deploy Application Version
        command: >
          env > /tmp/env_file;
          docker run --env-file=/tmp/env_file quay.io/deployhub/compupdate:latest  
          deploy
          --dhuser "$<< parameters.dhuser >>"
          --dhpass "$<< parameters.dhpass >>"
          --dhurl "$<< parameters.dhurl >>"
          --appname "<< parameters.application >>"
          --appversion "<< parameters.appversion >>"          
          --deployenv "<< parameters.environment >>"

  deploy_component:
    description: "Deploys an Application Version to an Environment based on a Component"
    parameters:
      dhuser:
        description: "Name of env var storing UserId to access DeployHub"
        type: env_var_name
        default: DH_USERID
      dhpass:
        description: "Name of env var storing dhpass to access DeployHub"
        type: env_var_name
        default: DH_PASSWORD
      dhurl:
        description: "Name of env var storing URL to the DeployHub Server"
        type: env_var_name
        default: DH_SERVERURL
      component:
        description: "Component Name to Deploy"
        type: string            

    steps:
    - run:
        name: Deploy Application Version base on a Component
        command: >
          env > /tmp/env_file;
          docker run --env-file=/tmp/env_file quay.io/deployhub/compupdate:latest  
          deploy
          --dhuser "$<< parameters.dhuser >>"
          --dhpass "$<< parameters.dhpass >>"
          --dhurl "$<< parameters.dhurl >>"
          --compname "<< parameters.component >>"

  envscript:
    description: "Generate the environment variable script from the TOML file"
    parameters:
      envvars:
        description: "Name of the input environment TOML file"
        type: string
      envvars_sh:
        description: "Name of output shell script name"
        type: string
    steps:
    - run:
        name: Create env script
        command: |
          docker create -v /home/circleci/project --name envscript quay.io/deployhub/compupdate:latest /bin/true;
          docker cp << parameters.envvars >> envscript:/home/circleci/project/envvars.toml;
          docker run --volumes-from envscript quay.io/deployhub/compupdate:latest envscript --envvars /home/circleci/project/envvars.toml --envvars_sh /home/circleci/project/bash_env.sh;
          docker cp envscript:/home/circleci/project/bash_env.sh /tmp/bash_env.sh;
          cat /tmp/bash_env.sh >> << parameters.envvars_sh >>;
          
jobs:
  approve_job:
    description: "Approve an Application Version"
    parameters:
      dhuser:
        description: "Name of env var storing UserId to access DeployHub"
        type: env_var_name
        default: DH_USERID
      dhpass:
        description: "Name of env var storing dhpass to access DeployHub"
        type: env_var_name
        default: DH_PASSWORD
      dhurl:
        description: "Name of env var storing URL to the DeployHub Server"
        type: env_var_name
        default: DH_SERVERURL
      application:
        description: "Application Name to Approve"
        type: string
      appversion:
        description: "Application Version to Approve"
        type: string        
    executor: default
    steps:
      - approve:
          dhuser: << parameters.dhuser >>
          dhpass: << parameters.dhpass >>
          dhurl: << parameters.dhurl >>
          application:  << parameters.application >>
          appversion:  << parameters.appversion >>
  move_job:
    description: "Move an Application Version through the pipeline"
    parameters:
      dhuser:
        description: "Name of env var storing UserId to access DeployHub"
        type: env_var_name
        default: DH_USERID
      dhpass:
        description: "Name of env var storing dhpass to access DeployHub"
        type: env_var_name
        default: DH_PASSWORD
      dhurl:
        description: "Name of env var storing URL to the DeployHub Server"
        type: env_var_name
      application:
        description: "Application Name to move"
        type: string
      appversion:
        description: "Application Version to move"
        type: string   
      from_domain:
        description: "Pipeline stage to move from"
        type: string
      move_task:
        description: "'Move Task' used to move the application version to desired stage"
        type: string 
    executor: default
    steps:
      - move:
          dhuser: << parameters.dhuser >>
          dhpass: << parameters.dhpass >>
          dhurl: << parameters.dhurl >>
          application:  << parameters.application >>
          appversion:  << parameters.appversion >>
          from_domain:  << parameters.from_domain >>
          move_task:  << parameters.move_task >>   
  deploy_job:
    description: "Deploy an Application Version to an Environment"
    parameters:
      dhuser:
        description: "Name of env var storing UserId to access DeployHub"
        type: env_var_name
        default: DH_USERID
      dhpass:
        description: "Name of env var storing dhpass to access DeployHub"
        type: env_var_name
        default: DH_PASSWORD
      dhurl:
        description: "Name of env var storing URL to the DeployHub Server"
        type: env_var_name
        default: DH_SERVERURL
      application:
        description: "Application Name to Deploy"
        type: string
      appversion:
        description: "Application Version to Deploy"
        type: string        
      environment:
        description: "Environment to Deploy to"
        type: string   
    executor: default
    steps:
      - deploy:
          dhuser: << parameters.dhuser >>
          dhpass: << parameters.dhpass >>
          dhurl: << parameters.dhurl >>
          application:  << parameters.application >>
          appversion:  << parameters.appversion >>          
          environment:  << parameters.environment >>     
  deploy_component_job:
    description: "Deploy an Application Version to an Environment based on a Component"
    parameters:
      dhuser:
        description: "Name of env var storing UserId to access DeployHub"
        type: env_var_name
        default: DH_USERID
      dhpass:
        description: "Name of env var storing dhpass to access DeployHub"
        type: env_var_name
        default: DH_PASSWORD
      dhurl:
        description: "Name of env var storing URL to the DeployHub Server"
        type: env_var_name
        default: DH_SERVERURL
      component:
        description: "Component Name to Deploy"
        type: string
    executor: default
    steps:
      - deploy_component:
          dhuser: << parameters.dhuser >>
          dhpass: << parameters.dhpass >>
          dhurl: << parameters.dhurl >>
          component:  << parameters.component >>                        
  microservice_version_update_job:
    description: "Update the microservice or component with git and build data"
    parameters:
      dhuser:
        description: "Name of env var storing UserId to access DeployHub"
        type: env_var_name
        default: DH_USERID
      dhpass:
        description: "Name of env var storing dhpass to access DeployHub"
        type: env_var_name
        default: DH_PASSWORD
      dhurl:
        description: "Name of env var storing URL to the DeployHub Server"
        type: env_var_name
        default: DH_SERVERURL
      application:
        description: "Application Name to associate the component to"
        type: string
      appversion:
        description: "Application Version to associate the component to"
        type: string 
      compname:
        description: "Component Name being updated"
        type: string
      compversion:
        description: "Component Version being updated"
        type: string 
      comptype:
        description: "Type of component, --docker or --file"
        type: string   
      helmchart:
        description: "Helm Chart Name"
        type: string   
      dockersha:
        description: "sha of the container"
        type: string  
      dockerrepo:
        description: "docker repo from push"
        type: string  
      dockertag:
        description: "docker tag for the image"
        type: string        
      builddate:
        description: "Build Date"
        type: string
      gitrepo:
        description: "Git Repo Name"
        type: string
      giturl:
        description: "Git Url"
        type: string
      gitcommit:
        description: "Git Commit"
        type: string
      gitbranch:
        description: "Git Branch"
        type: string
      gittag:
        description: "Git Tag"
        type: string    
      buildid:
        description: "Build Id"
        type: string
      buildurl:
        description: "Build Url"
        type: string  
      buildnumber:
        description: "Build Number"
        type: string
      customaction:
        description: "Custom Action"
        type: string
      preaction:
        description: "Pre Action"
        type: string 
      postaction:
        description: "Post Action"
        type: string                    
    executor: default         
    steps:
      - microservice_version_update:
          dhuser: << parameters.dhuser >>
          dhpass: << parameters.dhpass >>
          dhurl: << parameters.dhurl >>
          application: << parameters.application >>
          appversion: << parameters.appversion >>
          compname: << parameters.compname >>
          compversion: << parameters.compversion >>
          comptype: << parameters.comptype >>
          helmchart: << parameters.helmchart >>
          dockersha: << parameters.dockersha >>
          builddate: << parameters.builddate >>
          dockerrepo: << parameters.dockerrepo >>
          dockertag: << parameters.dockertag >>          
          giturl: << parameters.giturl >>
          gitrepo: << parameters.gitrepo >>
          gitcommit: << parameters.gitcommit >>
          gitbranch: << parameters.gitbranch >>
          gittag: << parameters.gittag >>
          buildid: << parameters.buildid >>
          buildurl: << parameters.buildurl >>
          buildnumber: << parameters.buildnumber >>
          customaction: << parameters.customaction >>
          preaction: << parameters.preaction >>
          postaction: << parameters.postaction >>
  envscript_job:
    description: "Generate the environment variable script from the TOML file"
    parameters:
      envvars:
        description: "Name of the input environment TOML file"
        type: string
      envvars_sh:
        description: "Name of output shell script name"
        type: string  
    executor: default
    steps:
      - envscript:
          envvars: << parameters.envvars >>
          envvars_sh: << parameters.envvars_sh >>  
